---
title: Shape
order: 40
---

= Shape

Use these CSS custom properties to adjust the visual style of component shapes.



== Usage

[.example]
--
[source,typescript, role=hidden]
----
include::{root}/frontend/demo/foundation/lumo-tokens.ts[hidden]
----

[source,typescript]
----
include::{root}/frontend/demo/foundation/lumo-tokens.ts[tags=style]
----
--


== Border Radius

The border radius values are defined as em by default, so they scale with the font size.

++++
<style>
.custom-property-preview.shape {
  background-color: transparent;
}

.custom-property-preview.shape::after {
  content: none;
}

.custom-property-preview.shape::before {
  content: "";
  width: 2em;
  height: 2em;
  padding: 0;
  border-radius: var(--value);
  border: 1px solid;
}

.custom-property-preview.shape.l::before {
  width: 2.75em;
  height: 2.75em;
}

.custom-property-preview.shape.s::before {
  width: 1.5em;
  height: 1.5em;
}
</style>
++++

[.property-listing.previews, cols="1,>1"]
|===
| Description | CSS Custom Property

| [.preview(--lumo-border-radius-l).shape.l]*Large* +
Dialogs, cards, and other larger container elements.
| [custom-property]#--lumo-border-radius-l#

| [.preview(--lumo-border-radius-m).shape.m]*Medium* +
Buttons and input fields, and most other normal sized UI elements.
| [custom-property]#--lumo-border-radius-m#

| [.preview(--lumo-border-radius-s).shape.s]*Small* +
Checkboxes and other small elements that could turn into circles with a too large border radius.
| [custom-property]#--lumo-border-radius-s#
|===
